stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  - mavendeploy
 
maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn package -B
    
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar
  
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/PuzzleGame/gradlew
  script:
    - cd Frontend/PuzzleGame
    - ./gradlew build
  artifacts:
    paths:
      - Android_test/app/build/outputs/
      
android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/PuzzleGame/gradlew
  script:
    - cd Frontend/PuzzleGame
    - ./gradlew test
    
autoDeploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo.service
    - sudo systemctl start system-web-demo.service
